apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Chart.Name}}-config
  namespace: {{.Values.common.namespace}}
data:
{{- range $k, $v := .Values.todoapp.configmap}}
  {{$k}}: {{$v | quote}}
{{- end}}